# Generated by Django 5.0.3 on 2024-04-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_amount_alter_total_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='total',
            name='total',
            field=models.CharField(max_length=200),
        ),
    ]
