# Generated by Django 5.0.3 on 2024-04-03 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expense_amount_alter_total_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='total',
            old_name='total',
            new_name='totals',
        ),
    ]
