# Generated by Django 5.0.3 on 2024-04-03 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_rename_total_total_totals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='total',
            old_name='totals',
            new_name='totalspent',
        ),
    ]
