# Generated by Django 5.0.3 on 2024-04-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(max_length=200)),
                ('sub1marks', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sub2marks', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sub3marks', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
