# Generated by Django 5.0.3 on 2024-04-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1name', models.CharField(max_length=200)),
                ('sub1marks', models.IntegerField()),
                ('sub2name', models.CharField(max_length=200)),
                ('sub2marks', models.IntegerField()),
                ('sub3name', models.CharField(max_length=200)),
                ('sub3marks', models.IntegerField()),
            ],
        ),
    ]
