# Generated by Django 5.0.3 on 2024-04-04 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancerecord',
            old_name='student_name',
            new_name='subject_name',
        ),
    ]
